#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# $1 = previous HEAD ref
# $2 = new HEAD ref
# $3 = flag (1 = branch checkout, 0 = file checkout)

# Only run on branch checkout
if [ "$3" = "1" ]; then
  bun run validate:branch-name
fi

exit 0 # Always exit 0 for post-checkout, it's informational
