#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged for code formatting and linting
# bun lint-staged

# Run eslint check
echo "Running eslint check..."
bun run eslint:check

# Run type checking
echo "Running type checking..."
bun run typecheck

# Run prettier fix
echo "Running prettier fix..."
bun run prettier:fix

# Run tests
# echo "Running tests..."
# bun run test
